#let gets = $arrow.l$
#let sim = $tilde.op$

#let ADPP = "AD++"
#let ADPP-full-name = "Algorithm Distillation ++"
#let Act = $a$
#let Actions = $cal(A)$
#let Buffer = $cal(D)$
#let Dataset = $cal(D)$
#let History = $h$
#let Loss = $cal(L)$
#let LLM = $upright("LLM")$
#let Obs = $x$
#let Policy = $pi$
#let Prob = $P$
#let ProbTar = $accent(P, hat)$
#let QValue = $Q$
#let QEst = $accent(QValue, tilde)$
#let QTar = $accent(QValue, hat)$
#let Recency = $c$
#let Rew = $r$
#let State = $s$
#let Task = $cal(T)$
#let Ter = $b$
#let Traj = $tau$
#let Value = $V$
#let VEst = $accent(Value, tilde)$

#let Highlight(s) = text(fill: red, s)